# -*- coding: utf-8 -*-
"""
/***************************************************************************
 RandomForestClassifier
                                 A QGIS plugin
 -
 Generated by Plugin Builder: http://g-sherman.github.io/Qgis-Plugin-Builder/
                             -------------------
        begin                : 2020-06-01
        copyright            : (C) 2020 by -
        email                : -
        git sha              : $Format:%H$
 ***************************************************************************/

/***************************************************************************
 *                                                                         *
 *   This program is free software; you can redistribute it and/or modify  *
 *   it under the terms of the GNU General Public License as published by  *
 *   the Free Software Foundation; either version 2 of the License, or     *
 *   (at your option) any later version.                                   *
 *                                                                         *
 ***************************************************************************/
 This script initializes the plugin, making it known to QGIS.
"""


# noinspection PyPep8Naming
def classFactory(iface):  # pylint: disable=invalid-name
    """Load RandomForestClassifier class from file RandomForestClassifier.

    :param iface: A QGIS interface instance.
    :type iface: QgsInterface
    """
    #
    from .RandomForestClassifier import RandomForestClassifier
    return RandomForestClassifier(iface)
